#端口号配置
server:
  port: 8002

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#spring配置
spring:
  application:
    name: BusinessService
  datasource:
    ##type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manufacturer?useUnicode=true&CharacterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: rent_tx_group



#Eureka的配置 配置服务注册到哪里  defaultZone是一个请求，表示服务注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: BusinessService-8002

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


logging:
    level:
      com.ffk.dao: debug