#端口号配置
server:
  port: 8007

#mybatis配置
mybatis:
  type-aliases-package: com.ffk.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#spring配置
spring:
  application:
    name: PlatformService
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&CharacterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: rent_tx_group


hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#Eureka的配置 配置服务注册到哪里  defaultZone是一个请求，表示服务注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: PlatformService-8007


logging:
  level:
    com.ffk.dao: debug


ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000