#端口号配置
server:
  port: 8006

#spring配置
spring:
  application:
    name: PayService
  cloud:
    alibaba:
      seata:
        tx-service-group: rent_tx_group

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


#Eureka的配置 配置服务注册到哪里  defaultZone是一个请求，表示服务注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: PayService-8006